CREATE DATABASE SOCHUNG
USE SOCHUNG

CREATE TABLE NguoiDung (
    IdNguoiDung INT PRIMARY KEY IDENTITY,
    TenDangNhap NVARCHAR(50) NOT NULL UNIQUE,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    MatKhau NVARCHAR(255) NOT NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE()
)

CREATE TABLE DanhMucChiTieu (
    IdDanhMuc INT PRIMARY KEY IDENTITY,
    IdNguoiDung INT NULL,
    TenDanhMuc NVARCHAR(100) NOT NULL,
    Icon NVARCHAR(50) NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_DanhMuc_NguoiDung FOREIGN KEY (IdNguoiDung) REFERENCES NguoiDung(IdNguoiDung)
)

CREATE TABLE ChiTieu (
    IdChiTieu INT PRIMARY KEY IDENTITY,
    IdNguoiDung INT NOT NULL,
    IdDanhMuc INT NOT NULL,
    SoTien DECIMAL(12,2) NOT NULL CHECK (SoTien > 0),
    NoiDung NVARCHAR(255) NULL,
    NgayChi DATE NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_ChiTieu_NguoiDung FOREIGN KEY (IdNguoiDung) REFERENCES NguoiDung(IdNguoiDung),

    CONSTRAINT FK_ChiTieu_DanhMuc FOREIGN KEY (IdDanhMuc) REFERENCES DanhMucChiTieu(IdDanhMuc)
)

CREATE TABLE CongNo (
    IdCongNo INT PRIMARY KEY IDENTITY,
    IdNguoiDung INT NOT NULL,
    TenNguoi NVARCHAR(100) NOT NULL,
    SoTien DECIMAL(12,2) NOT NULL CHECK (SoTien > 0),

    LoaiCongNo NVARCHAR(20) NOT NULL
    CHECK (LoaiCongNo IN ('NO','CHO_VAY')),

    NoiDung NVARCHAR(255) NULL,
    HanTra DATE NULL,

    TrangThai NVARCHAR(20) NOT NULL
    DEFAULT 'CHUA_TRA'
    CHECK (TrangThai IN ('CHUA_TRA','TRA_MOT_PHAN','DA_TRA')),

    NgayPhatSinh DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_CongNo_NguoiDung FOREIGN KEY (IdNguoiDung) REFERENCES NguoiDung(IdNguoiDung)
)

CREATE TABLE ThanhToanCongNo (
    IdThanhToan INT PRIMARY KEY IDENTITY,
    IdCongNo INT NOT NULL,
    SoTienThanhToan DECIMAL(12,2) NOT NULL CHECK (SoTienThanhToan > 0),
    NgayThanhToan DATE NOT NULL DEFAULT GETDATE(),
    GhiChu NVARCHAR(255) NULL,

    CONSTRAINT FK_ThanhToan_CongNo FOREIGN KEY (IdCongNo) REFERENCES CongNo(IdCongNo)
)
